using LogicaCSharp;
using System.Reflection.PortableExecutable;

//Operacoes.Main(args);
//Voto.Main(args);
//Ifternario.Main(args);
//FormasG.Main(args);
//Semana.Main(args);
//Soma100PrimerosNumeros.Main(args);
//While.Main(args);
//DoWhile.Main(args);
//QuadradosNumerosInteiros.Main(args);
//CharString.Main(args);
//ExemplosMath.Main(args);
//VetorMatriz.Main(args);
//ForEachVetores.Main(args); 
//SystemLinq.Main(args);
//SucessoreAntecessor.Main(args);
//ForEachMatriz2D.Main(args);
//Somatorio.Main(args);
//MetodosComParametros.Main(args);
//MetodoSobrecarga.Main(args);
//CestaDeFrutas.Main(args);
//TabuadaArray.Main(args);
//Tabuada10.Main(args);
//ParOuImpar.Main(args);
//Media.Main(args);
//Somando.Main(args);
//Advinhacao.Main(args);
//InverterArray.Main(args);
Cor.Main(args);